services:
    liilo_mangopay_service:
        class: %liilo_mangopay_service.class%
        arguments:
            client_id:            %liilo_mangopay.client_id%
            client_password:      %liilo_mangopay.client_password%
            temp_folder:          %liilo_mangopay.temp_folder%
            prod:                 %liilo_mangopay.prod%