services:
    liilo_mangopay_service:
        class: "%liilo_mangopay_service.class%"
        arguments: ["%liilo_mangopay_service.client_id%", "%liilo_mangopay_service.client_password%", "%liilo_mangopay_service.temp_folder%", "%liilo_mangopay_service.prod%"]